### ISSUE TITLE
Files full of rebase conflicts

### ISSUE THREAD

**Issue by mallardduck** [ace411/Bingo-Framework#4]
Looking over the repos code I'm seeing a **large** number of files include rebase conflict lines.

For example:

- https://github.com/ace411/Bingo-Framework/blob/master/composer.json#L13
- https://github.com/ace411/Bingo-Framework/blob/master/App/Config.php#L77
- https://github.com/ace411/Bingo-Framework/blob/master/Core/Controller.php#L53

And more...

**Comment by ace411** [comment]
I'll fix it as soon as I can. I'm currently swamped. Thank you for noticing and pointing out the faults.

**Comment by ace411** [comment]
Fixed. Thanks for showing patience.
